# Generated by Django 5.2 on 2025-04-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        ('vehicles', '0002_remove_vehicle_currently_assigned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainervehicle',
            options={'ordering': ['trainer', 'vehicle']},
        ),
        migrations.RemoveField(
            model_name='trainervehicle',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='trainervehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='trainervehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='trainervehicle',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='trainervehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='trainervehicle',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='vehicles.vehicle'),
        ),
    ]
