# Generated by Django 5.1.6 on 2025-02-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trainers.trainer'),
        ),
        migrations.AddField(
            model_name='student',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_set', to='trainers.trainer'),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
