# Generated by Django 5.2 on 2025-04-04 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course_trainingpackage_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.studentpackage'),
        ),
    ]
