# Generated by Django 5.2 on 2025-04-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_payment_student_package'),
        ('vehicles', '0002_remove_vehicle_currently_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_purchased_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='vehicles.vehicle'),
        ),
    ]
