# Generated by Django 5.2 on 2025-04-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_has_purchased_session_student_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='students.vehicle'),
        ),
    ]
