# Generated by Django 5.2 on 2025-04-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='currently_assigned',
        ),
        migrations.AlterUniqueTogether(
            name='vehicleassignmenthistory',
            unique_together={('vehicle', 'assigned_date')},
        ),
    ]
